<?xml version="1.0" encoding="utf-8"?>
<assemblies timestamp="09/08/2017 11:53:01">
  <assembly name="C:\Users\pagangil\Documents\Visual Studio 2017\Projects\xUnit\xUnit\bin\Debug\xUnit.DLL" environment="64-bit .NET 4.0.30319.42000 [collection-per-class, parallel (12 threads)]" test-framework="xUnit.net 2.2.0.3545" run-date="2017-09-08" run-time="11:53:01" config-file="C:\Users\pagangil\Documents\Visual Studio 2017\Projects\xUnit\packages\xunit.runner.console.2.2.0\tools\xunit.console.exe.Config" total="2" passed="1" failed="1" skipped="0" time="0.405" errors="0">
    <errors />
    <collection total="2" passed="1" failed="1" skipped="0" name="Test collection for xUnit.Class1" time="0.240">
      <test name="xUnit.Class1.PassingTest" type="xUnit.Class1" method="PassingTest" time="0.0353707" result="Pass">
        <output><![CDATA[Xunittt passss test loggggg
]]></output>
      </test>
      <test name="xUnit.Class1.FailingTest" type="xUnit.Class1" method="FailingTest" time="0.2045073" result="Fail">
        <output><![CDATA[Xunittt failllll test loggggg
]]></output>
        <failure exception-type="Xunit.Sdk.EqualException">
          <message><![CDATA[Assert.Equal() Failure\r\nExpected: 5\r\nActual:   4]]></message>
          <stack-trace><![CDATA[   at xUnit.Class1.FailingTest() in c:\users\pagangil\documents\visual studio 2017\Projects\xUnit\xUnit\Class1.cs:line 36]]></stack-trace>
        </failure>
      </test>
    </collection>
  </assembly>
</assemblies>